Traceback (most recent call last):
  File "C:\Users\indro\miniconda3\envs\jb\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\indro\miniconda3\envs\jb\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indro\miniconda3\envs\jb\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indro\miniconda3\envs\jb\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\indro\miniconda3\envs\jb\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\indro\miniconda3\envs\jb\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\indro\miniconda3\envs\jb\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Import utilities

import sys
sys.path.append('/path/to/Utilities')

from Utilities.models_2_0 import *
from Utilities.plots_2_0 import *

# Excel spreadsheet and material name strings
excel_filename = 'F82H/F82H_data.xlsx'
material_name = "F82H"

# Font and marker sizes for plotting
f_size = 10 # font size
m_size = 25 # marker size

sigma_default = 3 # for confidence interal
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 6[0m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[0;32m      4[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend([38;5;124m'[39m[38;5;124m/path/to/Utilities[39m[38;5;124m'[39m)
[1;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mUtilities[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodels_2_0[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mUtilities[39;00m[38;5;21;01m.[39;00m[38;5;21;01mplots_2_0[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      9[0m [38;5;66;03m# Excel spreadsheet and material name strings[39;00m

[1;31mModuleNotFoundError[0m: No module named 'Utilities'

